version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12
    env_file:
      - .env
  s3:
    image: minio/minio
    env_file:
      - .env
    ports:
      - "9000:9000"
    command: minio server /data