# Generated by Django 4.1.5 on 2023-01-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_comment_post_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="posts_amount",
            field=models.IntegerField(default=0),
        ),
    ]
