# Generated by Django 4.1.5 on 2023-01-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_userprofile_posts_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_amount',
            field=models.IntegerField(default=0),
        ),
    ]
