# Generated by Django 4.1.5 on 2023-02-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_follow_user_followed_alter_follow_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="followd_user_id",
            field=models.PositiveIntegerField(default=None),
        ),
    ]
