# Generated by Django 4.1.5 on 2023-02-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
